version: "3.9"
services:
  ihub-loader:
    image: ihub-broker:0.0.1
    container_name: ihub-broker
    volumes: 
      - C:/Projectes/Docker/ihub-broker/logs:/opt/ihub-broker/logs
      - C:/Projectes/Docker/ihub-broker/settings.yaml:/opt/ihub-broker/settings.yaml
