version: "3.9"
services:
  ihub-loader:
    image: ihub-loader:0.0.2
    container_name: dc-ihub-loader
    volumes: 
      - C:/Projectes/Smart cities/test-ihub-loader-logs:/opt/ihub-loader/logs
    restart: always
