default:
  dev: true
  maxstart: 
  executions:
    - sf
    - local
    - perro

executions:
  sf:
    url: postgresql://sf:sf@192.168.0.45:5432/sf
    sql: SELECT * FROM contenidors_fcc_out
    period: 1

  local:
    url: postgresql://sf:sf@192.168.0.45:5432/sf
    sql: SELECT * FROM contenidors_fcc_out
    period: 2
