default:
  dev: true # usufull to know if we are in dev mode
  executions: # names of executions to run when the execution starts
    databases:
      - sf
  consumer:
    api: http://localhost:8080/buffering/{connectorName}
    user: admin
    passwd: admin
  
executions: # each process should has an unique name
  databases:
    sf:
      url: postgresql://sf:sf@192.168.0.45:5432/sf
      sql: SELECT * FROM contenidors_fcc_out
      connectorName: ReceiverTest1
      repeat: 5 # process executes every n seconds
      wait: 2 # process waits for n seconds to it's first execution 
      localId: gid

    recittyCalonge:
      url: mssql+pyodbc://sa:sa@SQL2017:1433/RecittyCalongeData?driver=ODBC+Driver+17+for+SQL+Server
      sql: select er.AA_IGM, er.AA_DES, er.AA_GEOM.STAsText() as GEOMETRY from E_RPARFIN er;
      connectorName: ReceiverTest1
      repeat: 5
      wait: 1
      localId: AA_IGM
  ftps:
    local:
      host: '192.168.0.155'
      port: 21
      user: fani
      passwd: 3icFWr9v
      file: data.xlsx
      repeat: 10
      wait: 1
      connectorName: ReceiverTest1
      locallId: c1

