executions: # names of executions to run when the execution starts
    - calonge-dev

definitions:
  calonge-dev:
    type: database
    url: postgresql://calonge_inventory_u:v1gMNG1knv@192.168.0.77:5432/calonge
    sql: "select * from data.gbi_posiciones_vehiculos gpv limit 100;"
    repeat_each_seconds: 5 # process executes every n seconds
    topic: buffering
    bootstrap_server: 192.168.0.77:9094
