default:
  dev: true
  executions:
    - sf
    - local
    - perro

executions:
  sf:
    url: postgresql://sf:sf@192.168.0.45:5432/sf
    sql: SELECT * FROM contenidors_fcc_out
    each: 5
    wait: 10

  local:
    url: postgresql://sf:sf@192.168.0.45:5432/sf
    sql: SELECT * FROM contenidors_fcc_out
    each: 20
    wait: 4
