default:
  dev: true # usufull to know if we are in dev mode
  executions: # names of executions to run when the execution starts
    databases:
      - calonge-dev
  consumer:
    api: http://localhost:8080/buffering/{connectorName}
    user: admin
    passwd: admin
  
executions: # each process should has an unique name
  databases:
    calonge-dev:
      url: postgresql://calonge_inventory_u:v1gMNG1knv@192.168.0.77:5432/calonge
      sql: "select * from data.gbi_posiciones_vehiculos gpv limit 100;"
      connectorName: Buffering
      repeat: 5 # process executes every n seconds
      wait: 4 # process waits for n seconds to it's first execution 
      localId: gid

